version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysqldb
    hostname: localhost
    ports:
    - "3307:3306"
    volumes:
    - mysql:/var/lib/mysql
    - ./my.cnf:/etc/my.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=cms_sys
    command: ['mysqld',
              '--innodb-buffer-pool-size=20M',
              '--character-set-server=utf8',
              '--collation-server=utf8_general_ci',
              '--default-time-zone=+8:00',
              '--lower-case-table-names=1']
volumes:
  mysql: