version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysqldb
    hostname: localhost
    ports:
    - "3306:3306"
    volumes:
    - mysql:/var/lib/mysql
    - ./my.cnf:/etc/my.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=cms_sys
volumes:
  mysql: